# Generated by Django 5.1.4 on 2024-12-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomeUsuario', models.CharField(max_length=255)),
                ('descricaoUsuario', models.TextField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('practice_license_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomeUsuario', models.CharField(max_length=255)),
                ('descricaoUsuario', models.TextField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
