# Generated by Django 5.1.4 on 2024-12-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='formacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='horario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='consultou',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='processos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
