# Generated by Django 5.1.4 on 2024-12-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_cliente_phone_number_advogado_formacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='consultou',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='processos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fichaCriminal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
